const USER_TYPES ={
    USER_SIGNIN_START:'USER_SIGNIN_START',
    USER_SIGNIN_SUCCESS:'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILURE:'USER_SIGNIN_FAILURE',
    USER_LOGOUT_START:'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS:'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE:'USER_LOGOUT_FAILURE',
    USER_ENTERED_WRONG_CREDENTIALS:'USER_ENTERED_WRONG_CREDENTIALS'
}

export default USER_TYPES;