const All_PASSANGER_TYPES={
    ALL_PASSANGER_INFO_FETCHING_START: 'ALL_PASSANGER_INFO_FETCHING_START',
    ALL_PASSANGER_INFO_FETCHING_FAILURE:'ALL_PASSANGER_INFO_FETCHING_FAILURE',
    ALL_PASSANGER_INFO_FETCHING_SUCCESS: 'ALL_PASSANGER_INFO_FETCHING_SUCCESS',
    REMOVE_FETCHED_PASSENGERS:  'REMOVE_FETCHED_PASSENGERS'
}

export default All_PASSANGER_TYPES;