const All_PASSANGER_TYPES={
    ALL_PASSANGER_INFO_FETCHING_START: 'ALL_PASSANGER_INFO_FETCHING_START',
    ALL_PASSANGER_INFO_FETCHING_FAILURE:'ALL_PASSANGER_INFO_FETCHING_FAILURE',
    ALL_PASSANGER_INFO_FETCHING_SUCCESS: 'ALL_PASSANGER_INFO_FETCHING_SUCCESS',
    REMOVE_FETCHED_PASSENGERS:  'REMOVE_FETCHED_PASSENGERS',
    SET_SELECTED_PASSENGER_SEAT_NO:'SET_SELECTED_PASSENGER_SEAT_NO',
    SELECT_NEW_SEAT:'SELECT_NEW_SEAT',
    CHANGE_DISPLAY_BUTTON_NEXT:'CHANGE_DISPLAY_BUTTON_NEXT'
}

export default All_PASSANGER_TYPES;